#pragma once
/*
 * snowvi_ghash.hpp
 *
 * Accelerated GHASH (GF(2^128), NIST SP 800-38D) for SNOW-Vi-GCM, a drop-in
 * replacement for a bitwise `ghash` reference with the identical
 * signature and identical output.
 *
 * Compile-time dispatch of the field multiply:
 *   - ARM with crypto extensions (Pi 5, -march=armv8.2-a+crypto) -> PMULL
 *   - x86 with PCLMUL (dev/validation host)                       -> PCLMULQDQ
 *   - anything else (Pi Zero 2 W, A53, no crypto extensions)      -> 4-bit Shoup table
 *
 * ACCEPTANCE TEST (snowvi_ghash_test.cpp): every path must reproduce the output
 * of a bitwise gmul128/ghash reference byte for byte.
 *   - table  path: PASS, 300,000 random (X,H) multiplies + full ghash over
 *     random AAD/ciphertext (validated on x86).
 *   - PCLMUL path: PASS, same battery (validated on x86).
 *   - PMULL  path: structurally identical to the validated PCLMUL sequence
 *     (same Karatsuba product, same <<1 for the GCM bit reflection, same
 *     two-phase reduction); its acceptance test is compiled-and-run on the Pi 5
 *     against the table path, since this x86 host cannot execute PMULL.
 *
 * The reduction follows Gueron & Kounavis, "Intel Carry-Less Multiplication
 * Instruction and its Usage for Computing the GCM Mode".
 */
#include <cstdint>
#include <cstring>
#include <cstddef>

#if defined(__ARM_FEATURE_CRYPTO) || (defined(__aarch64__) && defined(__ARM_FEATURE_AES))
  #define SNOWVI_GHASH_PMULL 1
  #include <arm_neon.h>
#elif defined(__PCLMUL__)
  #define SNOWVI_GHASH_PCLMUL 1
  #include <wmmintrin.h>
  #include <tmmintrin.h>
  #include <emmintrin.h>
#else
  #define SNOWVI_GHASH_TABLE 1
#endif

namespace snowvi_ghash {

using u8  = uint8_t;
using u16 = uint16_t;

// ---------------------------------------------------------------------------
// Portable 4-bit Shoup table multiply (also the reference used to build the
// per-packet table). Correct by construction: the nibble multiples of H are
// generated by repeated multiply-by-x, and reduction of the 4 bits shifted out
// each step comes from the precomputed, H-independent Rtab.
// ---------------------------------------------------------------------------
namespace detail {

inline void mul_x(u8 A[16]) {                 // multiply by the field generator x
    u8 lsb = A[15] & 1;
    for (int j = 15; j > 0; j--) A[j] = (u8)((A[j] >> 1) | ((A[j-1] & 1) << 7));
    A[0] >>= 1;
    if (lsb) A[0] ^= 0xe1;
}

inline const u16* Rtable() {                  // reduction of a 4-bit overflow
    static u16 R[16];
    static bool done = false;
    if (!done) {
        for (int v = 0; v < 16; v++) {
            u8 E[16] = {0}; E[15] = (u8)v;
            for (int t = 0; t < 4; t++) mul_x(E);
            R[v] = (u16)((E[0] << 8) | E[1]);
        }
        done = true;
    }
    return R;
}

struct Table { u8 M[16][16]; };

inline void build(Table& T, const u8 H[16]) {
    u8 P8[16], P4[16], P2[16], P1[16];
    memcpy(P8, H, 16);
    memcpy(P4, P8, 16); mul_x(P4);
    memcpy(P2, P4, 16); mul_x(P2);
    memcpy(P1, P2, 16); mul_x(P1);
    for (int n = 0; n < 16; n++) {
        u8 z[16] = {0};
        if (n & 8) for (int j = 0; j < 16; j++) z[j] ^= P8[j];
        if (n & 4) for (int j = 0; j < 16; j++) z[j] ^= P4[j];
        if (n & 2) for (int j = 0; j < 16; j++) z[j] ^= P2[j];
        if (n & 1) for (int j = 0; j < 16; j++) z[j] ^= P1[j];
        memcpy(T.M[n], z, 16);
    }
}

inline void shr4(u8 A[16]) {
    for (int j = 15; j > 0; j--) A[j] = (u8)((A[j] >> 4) | ((A[j-1] & 0xF) << 4));
    A[0] >>= 4;
}

inline void gmul_table(u8 Z[16], const u8 X[16], const Table& T) {
    const u16* R = Rtable();
    u8 acc[16] = {0};
    for (int k = 31; k >= 0; k--) {
        int byte = k >> 1;
        int nib  = (k & 1) ? (X[byte] & 0xF) : (X[byte] >> 4);
        u8 v = acc[15] & 0xF;
        shr4(acc);
        acc[0] ^= (u8)(R[v] >> 8);
        acc[1] ^= (u8)(R[v] & 0xFF);
        for (int j = 0; j < 16; j++) acc[j] ^= T.M[nib][j];
    }
    memcpy(Z, acc, 16);
}

#if defined(SNOWVI_GHASH_PCLMUL)
inline __m128i gmul_x86(__m128i A, __m128i B) {
    const __m128i BSW = _mm_set_epi8(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15);
    __m128i a = _mm_shuffle_epi8(A, BSW), b = _mm_shuffle_epi8(B, BSW);
    __m128i t1 = _mm_clmulepi64_si128(a, b, 0x00);
    __m128i t2 = _mm_clmulepi64_si128(a, b, 0x01);
    __m128i t3 = _mm_clmulepi64_si128(a, b, 0x10);
    __m128i t4 = _mm_clmulepi64_si128(a, b, 0x11);
    t2 = _mm_xor_si128(t2, t3);
    t3 = _mm_slli_si128(t2, 8);
    t2 = _mm_srli_si128(t2, 8);
    t1 = _mm_xor_si128(t1, t3);
    t4 = _mm_xor_si128(t4, t2);
    __m128i t5 = _mm_srli_epi32(t1, 31), t6 = _mm_srli_epi32(t4, 31);
    t1 = _mm_slli_epi32(t1, 1); t4 = _mm_slli_epi32(t4, 1);
    __m128i t7 = _mm_srli_si128(t5, 12);
    t6 = _mm_slli_si128(t6, 4); t5 = _mm_slli_si128(t5, 4);
    t1 = _mm_or_si128(t1, t5); t4 = _mm_or_si128(t4, t6); t4 = _mm_or_si128(t4, t7);
    t5 = _mm_slli_epi32(t1, 31); t6 = _mm_slli_epi32(t1, 30); t7 = _mm_slli_epi32(t1, 25);
    t5 = _mm_xor_si128(t5, t6); t5 = _mm_xor_si128(t5, t7);
    t6 = _mm_srli_si128(t5, 4); t5 = _mm_slli_si128(t5, 12);
    t1 = _mm_xor_si128(t1, t5);
    __m128i t8 = _mm_srli_epi32(t1, 1), t9 = _mm_srli_epi32(t1, 2), t10 = _mm_srli_epi32(t1, 7);
    t8 = _mm_xor_si128(t8, t9); t8 = _mm_xor_si128(t8, t10); t8 = _mm_xor_si128(t8, t6);
    t1 = _mm_xor_si128(t1, t8);
    return _mm_shuffle_epi8(_mm_xor_si128(t4, t1), BSW);
}
#endif

#if defined(SNOWVI_GHASH_PMULL)
// ARM PMULL — a 1:1 mirror of gmul_x86 above (validated on x86); the intrinsics
// are the only difference. Acceptance test is on the Pi 5 vs the table path.
inline uint8x16_t rev128(uint8x16_t x){ uint8x16_t r=vrev64q_u8(x); return vextq_u8(r,r,8); }
inline uint8x16_t clmul(uint64x2_t a, uint64x2_t b, int ai, int bi){
    poly64_t x = (poly64_t)(ai? vgetq_lane_u64(a,1):vgetq_lane_u64(a,0));
    poly64_t y = (poly64_t)(bi? vgetq_lane_u64(b,1):vgetq_lane_u64(b,0));
    return vreinterpretq_u8_p128(vmull_p64(x,y));
}
inline void gmul_arm(u8 Z[16], const u8 X[16], const u8 H[16]){
    uint8x16_t a = rev128(vld1q_u8(X)), b = rev128(vld1q_u8(H));
    uint64x2_t av = vreinterpretq_u64_u8(a), bv = vreinterpretq_u64_u8(b);
    uint8x16_t t1 = clmul(av,bv,0,0);
    uint8x16_t t2 = clmul(av,bv,1,0);
    uint8x16_t t3 = clmul(av,bv,0,1);
    uint8x16_t t4 = clmul(av,bv,1,1);
    t2 = veorq_u8(t2,t3);
    uint8x16_t zero = vdupq_n_u8(0);
    t3 = vextq_u8(zero,t2,8);      // << 8 bytes
    t2 = vextq_u8(t2,zero,8);      // >> 8 bytes
    t1 = veorq_u8(t1,t3);
    t4 = veorq_u8(t4,t2);
    uint32x4_t t1w=vreinterpretq_u32_u8(t1), t4w=vreinterpretq_u32_u8(t4);
    uint32x4_t t5=vshrq_n_u32(t1w,31), t6=vshrq_n_u32(t4w,31);
    t1w=vshlq_n_u32(t1w,1); t4w=vshlq_n_u32(t4w,1);
    uint8x16_t t5b=vreinterpretq_u8_u32(t5), t6b=vreinterpretq_u8_u32(t6);
    uint8x16_t t7b=vextq_u8(t5b,zero,12);       // srli_si128(t5,12)
    t6b=vextq_u8(zero,t6b,4);                   // slli_si128(t6,4)
    t5b=vextq_u8(zero,t5b,4);                   // slli_si128(t5,4)
    t1=vorrq_u8(vreinterpretq_u8_u32(t1w),t5b);
    t4=vorrq_u8(vorrq_u8(vreinterpretq_u8_u32(t4w),t6b),t7b);
    t1w=vreinterpretq_u32_u8(t1);
    uint32x4_t r5=vshlq_n_u32(t1w,31), r6=vshlq_n_u32(t1w,30), r7=vshlq_n_u32(t1w,25);
    uint8x16_t r5b=vreinterpretq_u8_u32(veorq_u32(veorq_u32(r5,r6),r7));
    uint8x16_t r6b=vextq_u8(r5b,zero,4);        // srli_si128(_,4)
    r5b=vextq_u8(zero,r5b,12);                  // slli_si128(_,12)
    t1=veorq_u8(vreinterpretq_u8_u32(t1w),r5b);
    t1w=vreinterpretq_u32_u8(t1);
    uint32x4_t s8=vshrq_n_u32(t1w,1), s9=vshrq_n_u32(t1w,2), s10=vshrq_n_u32(t1w,7);
    uint8x16_t s8b=veorq_u8(veorq_u8(vreinterpretq_u8_u32(s8),vreinterpretq_u8_u32(s9)),
                            vreinterpretq_u8_u32(s10));
    s8b=veorq_u8(s8b,r6b);
    t1=veorq_u8(vreinterpretq_u8_u32(t1w),s8b);
    vst1q_u8(Z, rev128(veorq_u8(t4,t1)));
}
#endif

} // namespace detail

// ---------------------------------------------------------------------------
// GHASH accumulation — standard GCM structure and signature.
// ---------------------------------------------------------------------------
inline void ghash(u8 tag_out[16], const u8 H[16],
                  const u8* aad, size_t aad_len,
                  const u8* ct,  size_t ct_len)
{
    u8 g[16] = {0}, blk[16];
#if defined(SNOWVI_GHASH_TABLE)
    detail::Table T; detail::build(T, H);
    #define SNOWVI_MUL(dst) detail::gmul_table((dst), (dst), T)
#elif defined(SNOWVI_GHASH_PCLMUL)
    __m128i Hx = _mm_loadu_si128((const __m128i*)H);
    #define SNOWVI_MUL(dst) do { __m128i gg=_mm_loadu_si128((const __m128i*)(dst)); \
        _mm_storeu_si128((__m128i*)(dst), detail::gmul_x86(gg, Hx)); } while(0)
#else
    #define SNOWVI_MUL(dst) detail::gmul_arm((dst), (dst), H)
#endif

    size_t off = 0;
    while (off < aad_len) {
        memset(blk, 0, 16);
        size_t n = (aad_len - off < 16) ? (aad_len - off) : 16;
        memcpy(blk, aad + off, n);
        for (int j = 0; j < 16; j++) g[j] ^= blk[j];
        SNOWVI_MUL(g);
        off += 16;
    }
    off = 0;
    while (off < ct_len) {
        memset(blk, 0, 16);
        size_t n = (ct_len - off < 16) ? (ct_len - off) : 16;
        memcpy(blk, ct + off, n);
        for (int j = 0; j < 16; j++) g[j] ^= blk[j];
        SNOWVI_MUL(g);
        off += 16;
    }
    uint64_t la = (uint64_t)aad_len * 8, lc = (uint64_t)ct_len * 8;
    for (int j = 0; j < 8; j++) blk[j]      = (u8)(la >> (56 - 8*j));
    for (int j = 0; j < 8; j++) blk[8 + j]  = (u8)(lc >> (56 - 8*j));
    for (int j = 0; j < 16; j++) g[j] ^= blk[j];
    SNOWVI_MUL(g);

    memcpy(tag_out, g, 16);
    #undef SNOWVI_MUL
}

} // namespace snowvi_ghash
